name: Cypress Tests
on: [pull_request]
  
jobs:
  cypress-run: 
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Cypress.io
        uses: cypress-io/github-action@v2.9.7
        with:
          start: npm start
        
      
